application: pelitaapp
version: 1
runtime: python27
api_version: 1
threadsafe: no

inbound_services:
- channel_presence

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: frontend.py
